apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: vulnerabilityreportvalidation
spec:
  crd:
    spec:
      names:
        kind: VulnerabilityReportValidation
      validation:
        openAPIV3Schema:
          type: object
          properties:
            sarif:
              type: object
              properties:
                version:
                  type: string
                runs:
                  type: array
                  items:
                    type: object
                    properties:
                      tool:
                        type: object
                        properties:
                          driver:
                            type: object
                            properties:
                              rules:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    properties:
                                      type: object
                                      properties:
                                        cvssv3_baseScore:
                                          type: number
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package vulnerabilityreportvalidation

        # Pass-through check that validates SARIF input
        violation[{"msg": msg}] {
          sarif := input.review.object.sarif

          # Check for high-severity vulnerabilities lacking remediation
          some run in sarif.runs
          some rule in run.tool.driver.rules
          rule.properties.cvssv3_baseScore >= 7.0
          rule.help.markdown == ""
          msg := sprintf("High-severity vulnerability %s lacks remediation steps.", [rule.id])
        }

        # Additional violations for SARIF data as defined in the template above
