apiVersion: config.ratify.deislabs.io/v1beta1
kind: Store
metadata:
  name: store-oras
spec:
  name: oras
  parameters: 
    cacheEnabled: true
    ttl: 10
    useHttp: true  
    authProvider:
      name: k8Secrets
      serviceAccountName: ratify-admin
      secrets: 
      - secretName: ratify-regcred
        namespace: gatekeeper-system