apiVersion: config.ratify.deislabs.io/v1beta1
kind: Verifier
metadata:
  name: verifier-schemavalidator
spec:
  name: schemavalidator
  artifactTypes: vnd.snyk.vulnerability-report.sarif.v1
  parameters:
    schemas:
      application/sarif+json: https://json.schemastore.org/sarif-2.1.0