apiVersion: apps/v1
kind: Deployment
metadata:
  name: unverified-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unverified-deployment
  template:
    metadata:
      labels:
        app: unverified-deployment
    spec:
      containers:
      - name: unverified-deployment
        image: iuriikogan/unverified:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            memory: 100Mi
            cpu: 100m