apiVersion: v1
kind: namespace
metadata:
  name: sbom-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verified-deployment
  namespace: sbom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verified-deployment
  template:
    metadata:
      labels:
        app: verified-deployment
    spec:
      containers:
      - name: verified-deployment
        image: iuriikogan/verified:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            memory: 100Mi
            cpu: 100m
        