apiVersion: Apps/v1
kind: Deployment
metadata:
  name: verified-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verified-deployment
  template:
    metadata:
      labels:
        app: verified-deployment
    spec:
      containers:
      - name: verified-deployment
        image: iuriikogan/verified-deployment:v1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: nginx
          runAsGroup: nginx
          fsGroup: nginx
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            memory: 100Mi
            cpu: 100m
        