---
apiVersion: v1
kind: Namespace
metadata:
  name: sbom-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: verified-deployment
  namespace: sbom-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verified-deployment
  template:
    metadata:
      labels:
        app: verified-deployment
    spec:
      containers:
      - name: verified-deployment
        image: docker.io/iuriikogan/snyk-juice-shop@sha256:97e7c99eb657bcc631232b747ff7904b2fea40b7301b7c4658e62f6ec6a82dfd
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            memory: 100Mi
            cpu: 100m
        